---
title: "idn_failure_point"
author: " "
date: " "
output: 
  html_document: 
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      dpi = 400)
library(tidyverse)
library(rio)
library(mgcv)
library(latex2exp)

theme_set(theme_bw()+
            theme(text=element_text(size = 12),
                  legend.box.margin = margin(-10,-10,-10,-10),
                  legend.position = "right",
                  strip.text = element_text(size= 9),
                  legend.text = element_text(size=10)))
```




###Loading data
```{r}
load(file = here::here("ss_data_all.RData"))
```


###Identify critical strain before stress fall sharply for all alloys,
```{r}

ss_dat_d <- ss_dat_all%>%
  unite("alloy_id",
        Mo:W,
        remove = FALSE)

temp <- ss_dat_d%>%
  group_by(alloy_id)%>%
  slice_head(n=1)%>%
  ungroup()%>%
  arrange(desc(Mo), desc(Nb),desc(Ta),desc(V),desc(W))

ss_dat_d <- ss_dat_d%>%
  mutate(alloy_cnt = factor(alloy_id,
                            levels = temp$alloy_id,
                            labels = 1:length(temp$alloy_id)))
```





```{r}
ss_dat_t <- ss_dat_d %>%
  filter(test_type == "Tension")

max_stress_t <- ss_dat_t %>%
  group_by(alloy_id, rep)%>% 
  summarize(stress = max(stress, na.rm = TRUE))%>%
  ungroup()


failure_points_t <- ss_dat_t%>%
                      inner_join(max_stress_t, 
                                 by = c("alloy_id", "stress", "rep"))


ss_dat_c <- ss_dat_d %>%
  filter(test_type == "Compresion")

max_stress_c <- ss_dat_c %>%
  group_by(alloy_id, rep)%>% 
  summarize(stress = max(stress, na.rm = TRUE))%>%
  ungroup()


failure_points_c <- ss_dat_c%>%
                      inner_join(max_stress_c, 
                                 by = c("alloy_id","stress", "rep"))
```



###Joining max_strain column to the dataset,
```{r}

max_strain_t = failure_points_t%>%
                select(strain , stress, alloy_id, rep)%>%
                rename(max_strain = strain,
                       max_stress = stress)


ss_dat_t = ss_dat_t%>%
            left_join(max_strain_t, 
                      by= c("alloy_id", "rep"))
                         


max_strain_c = failure_points_c%>%
                select(strain , stress, alloy_id, rep)%>%
                rename(max_strain = strain,
                       max_stress = stress)


ss_dat_c = ss_dat_c%>%
            left_join(max_strain_c, 
                      by= c("alloy_id", "rep"))

```




###Filtering based on critical strain, scaling the strain axis 0-1 and plotting to check,

```{r ss_coverage, fig.width=11, fig.height=3.5}
ss_dat_t_filtered = ss_dat_t %>%
                    filter(strain < max_strain | is.na(max_strain))%>%
                    group_by(alloy_id, rep)%>%
                    unite("alloy_rep_id", 
                          c("alloy_id", "rep"),
                          remove = F)%>%
                    mutate(scaled_strain = strain / max_strain,
                           scaled_stress = stress / max_stress,
                           alloy_id = factor(alloy_id),
                           rep_f = factor(rep),
                           alloy_rep_id = factor(alloy_rep_id))%>%
                    ungroup()%>%
  mutate(elements = (Mo>0) + (Nb>0) + (Ta>0) + (V>0) + (W>0))


ss_dat_c_filtered = ss_dat_c %>%
                    filter(strain < max_strain | is.na(max_strain))%>%
                    group_by(alloy_id, rep)%>%
                    unite("alloy_rep_id", 
                          c("alloy_id", "rep"),
                          remove = F)%>%
                    mutate(scaled_strain = strain / max_strain,
                           scaled_stress = stress / max_stress,
                           alloy_id = factor(alloy_id),
                           rep_f = factor(rep),
                           alloy_rep_id = factor(alloy_rep_id))%>%
                    ungroup()%>%
  mutate(elements = (Mo>0) + (Nb>0) + (Ta>0) + (V>0) + (W>0))

p1 <- ss_dat_t_filtered %>%
  unite("plot_id", 
        c("alloy_id", "rep"),
        remove = F)%>%
  filter(elements > 1)%>%
  mutate(elements = factor(elements))%>%
  ggplot(aes(x = scaled_strain,
             y = stress,
             group = plot_id,
             color = elements))+
  geom_line(alpha = 0.5)+
  scale_color_brewer("Elements",palette = "Dark2")+
  theme(legend.position = "right")+
  labs(y = TeX("Stress $\\sigma$ (GPa)"),
       x = TeX("Scaled Strain $\\tilde{\\epsilon}$"),
       title = "SS for Tension")


p2 <- ss_dat_c_filtered %>%
  unite("plot_id", 
        c("alloy_id", "rep"),
        remove = F)%>%
  filter(elements > 1)%>%
  mutate(elements = factor(elements))%>%
  ggplot(aes(x = scaled_strain,
             y = stress,
             group = plot_id,
             color = elements))+
  geom_line(alpha = 0.5)+
  scale_color_brewer("Elements",palette = "Dark2")+
  theme(legend.position = "right")+
  labs(y = TeX("Stress $\\sigma$ (GPa)"),
       x = TeX("Scaled Strain $\\tilde{\\epsilon}$"),
       title = "SS for Compression")

gridExtra::grid.arrange(p1, p2, nrow = 1)
```





```{r}
save(ss_dat_c_filtered,
     ss_dat_t_filtered,
     file = here::here("dat_filtered.RData"))
```



## Fit models 

### Orthonormal Basis Testing

```{r}
alr_id <- levels(ss_dat_t_filtered$alloy_rep_id)

temp_dat <- ss_dat_t_filtered%>%
          filter(alloy_rep_id==alr_id[1])
```

```{r}
source(here::here("Functions",
                  "utilities.R"))
```



### Othonormal basis fitting


```{r}
n_f <- 4:12
dat_gcv <- vector(mode = "list",
                   length = length(n_f))
lam_v <- c(0, 1, 10)
k <- 0

for(j in 1:3){
  for(i in 1:length(n_f)){
    k <- k + 1
    dat_orth_coefs_t <- fit_leg_basis_mod_fun(ss_dat = ss_dat_t_filtered%>%
                                              mutate(scaled_stress = stress),
                                            n_funs = n_f[i],
                                            lam = lam_v[j],
                                            intercept = T)
  
    dat_orth_coefs_c <- fit_leg_basis_mod_fun(ss_dat = ss_dat_c_filtered%>%
                                                mutate(scaled_stress = stress),
                                              n_funs = n_f[i],
                                              lam = lam_v[j],
                                              intercept = T)
    
    dat_gcv[[k]] <- dat_orth_coefs_c%>%
                      mutate(Test = "Com")%>%
                      bind_rows(dat_orth_coefs_t%>%
                                  mutate(Test = "Ten"))%>%
                      filter(coef_names == "gcv")%>%
                      mutate(nb = n_f[i],
                             lam = lam_v[j])
  }
}



```

```{r}
dat_gcv <- bind_rows(dat_gcv)
```

```{r}
temp <- ss_dat_c_filtered%>%
  filter(rep == 1)%>%
  ungroup()%>%
  filter(elements == 2,
         round(pmax(Mo,Nb,Ta,V,W),1) %in% c(0.1,0.3,0.5,0.7,0.9) 
         )%>%
  arrange(alloy_cnt)

#temp <- temp[-which(temp$alloy_cnt == 59),] #59 is the quanary with x =0.2 for all elements


id_train <- temp$alloy_cnt |> unique()
```


```{r fig.width=6, fig.height=3.4}
dat_gcv_avg <- dat_gcv%>%
                filter(alloy_cnt %in% id_train)%>%
                ungroup()%>%
                group_by(nb, lam, Test)%>%
                summarise(val = mean(val))
dat_gcv%>%
  filter(lam < 1)%>%
  mutate(nb = factor(nb),
         lam = factor(lam),
         Test = factor(Test, 
                       levels = c("Com","Ten"),
                       labels = c("Compression",
                                  "Tension")))%>%
  ggplot(aes(x = nb,
             y = val,
             colour = lam))+
  geom_boxplot()+
  facet_wrap(~Test)+
  theme_bw()+
  labs(y = "RMSE",
       x = "Number of Basis")
```

```{r rmse_basis, fig.width=5, fig.height=2.5}
dat_gcv_avg%>%
  filter(lam < 1)%>%
  mutate(Test = factor(Test, 
                       levels = c("Com","Ten"),
                       labels = c("Compression",
                                  "Tension")))%>%
  ggplot(aes(x = nb,
             y = val))+
  geom_line()+
  facet_wrap(~Test, scales = "free")+
  theme(legend.position = "right")+
  labs(y = "Average RMSE",
       x = "Number of Basis")
```

```{r rmse_basis_perc, fig.width=5, fig.height=2.5}
dat_gcv_avg%>%
  filter(lam < 1)%>%
  mutate(Test = factor(Test, 
                       levels = c("Com","Ten"),
                       labels = c("Compression",
                                  "Tension")))%>%
  group_by(Test)%>%
  arrange(nb)%>%
  mutate(val = (val - lag(val)) / lag(val) * 100 )%>%
  filter(nb > 4)%>%
  ggplot(aes(x = nb,
             y = val))+
  geom_line(linewidth = 1.5,
            colour = "blue")+
  facet_wrap(~Test, scales = "free")+
  theme(legend.position = "right")+
  geom_hline(yintercept = -0.25, 
             colour = "red",
             linetype = "dashed")+
  labs(y = "Change (%)",
       x = "Number of Basis")
```





```{r}
dat_orth_coefs_t <- fit_leg_basis_mod_fun(ss_dat = ss_dat_t_filtered%>%
                                            mutate(scaled_stress = stress),
                                          n_funs = 6,
                                          intercept = T)
dat_orth_coefs_c <- fit_leg_basis_mod_fun(ss_dat = ss_dat_c_filtered%>%
                                              mutate(scaled_stress = stress),
                                            n_funs = 6,
                                            intercept = T)
  
dat_orth_coefs_pred_t <- fit_leg_basis_mod_fun(ss_dat = ss_dat_t_filtered%>%
                                            mutate(scaled_stress = stress),
                                          n_funs = 6,
                                          intercept = T,
                                          return_pred = T)

dat_orth_coefs_pred_c <- fit_leg_basis_mod_fun(ss_dat = ss_dat_c_filtered%>%
                                            mutate(scaled_stress = stress),
                                          n_funs = 6,
                                          intercept = T,
                                          return_pred = T)
```





```{r}
dat_pred <- bind_rows(dat_orth_coefs_pred_c$preds,
                      dat_orth_coefs_pred_t$preds)
```

```{r}
dat_ids <- ss_dat_c_filtered%>%
            group_by(alloy_cnt)%>%
            slice_head(n= 1)

ids_labels <- c("Mo20_Nb80",
                "V50_W50",
                "Mo50_Nb25_Ta19_V00_W06")

dat_ids_plot <- dat_ids%>%
                  filter(Mo == 0.2, Nb == 0.8)%>%
  bind_rows(dat_ids%>%
                  filter(V == 0.5, W == 0.5),
                  dat_ids%>%
                  filter(Mo == 0.5, Nb == 0.25))

dat_ids_plot <- c(dat_ids_plot$alloy_cnt, 30)
```


```{r raw_combined, fig.width=6, fig.height=3.5, dpi = 400}
ss_dat_c%>%
  filter(alloy_cnt %in% dat_ids_plot,
         strain < 0.11)%>%
  bind_rows(
  ss_dat_t%>%
  filter(alloy_cnt %in% dat_ids_plot,
         strain < 0.11))%>%
  unite("alloy_rep_id", 
        c("alloy_id", "rep"),
        remove = F)%>%
  mutate(Rep = factor(rep),
         alloy_id = factor(alloy_cnt,
                           levels = dat_ids_plot,
                           labels = ids_labels))%>%
  ggplot(aes(x= strain,
             y = stress,
             linetype = Rep,
             group = alloy_rep_id,
             color = Rep))+
  geom_line()+
  facet_grid(test_type~alloy_id, scales = "free")+
  labs(x= TeX("Strain $\\epsilon$"),
       y = TeX("Stress $\\sigma$ (GPa)"),
       title = "Simulated Stress Strain Curves")+
  theme(legend.position = "bottom",
        axis.text = element_text(size = 7),
        strip.text.x = element_text(size= 6))
```


```{r trans_combined, fig.width=5, fig.height=3}
dat_pred%>%
  filter(alloy_cnt %in% dat_ids_plot)%>%
  unite("alloy_rep_id", 
        c("alloy_id", "rep"),
        remove = F)%>%
  filter(rep < 4)%>%
  mutate(Rep = factor(rep),
         alloy_id = factor(alloy_cnt,
                           levels = dat_ids_plot,
                           labels = ids_labels))%>%
  ggplot(aes(x= scaled_strain,
             group = alloy_rep_id))+
  geom_line(aes(y = stress),
            colour= "red",
            linewidth = 0.5)+
  geom_line(aes(y = pred_stress),
            colour = "blue",
            linewidth = 0.5,
            alpha = 0.75)+
  facet_grid(test_type~alloy_id, scales = "free")+
  labs(x= TeX("Scaled Strain ($\\epsilon^{*}$)"),
       y = TeX("Stress $\\sigma$ (GPa)"),
       title = "Stress-Strain Curves and Functional Fit")+
  theme(legend.position = "bottom",
        axis.text = element_text(size = 7),
        strip.text.x = element_text(size= 6))
```

```{r trans_combined_half, fig.width=5, fig.height=3}
dat_pred%>%
  filter(alloy_cnt %in% dat_ids_plot)%>%
  unite("alloy_rep_id", 
        c("alloy_id", "rep"),
        remove = F)%>%
  filter(rep < 4,
         scaled_strain > 0.75)%>%
  mutate(Rep = factor(rep),
         alloy_id = factor(alloy_cnt,
                           levels = dat_ids_plot,
                           labels = ids_labels))%>%
  ggplot(aes(x= scaled_strain,
             group = alloy_rep_id))+
    geom_line(aes(y = stress),
            colour= "red",
            linewidth = 0.5,
            alpha = 0.5)+
  geom_line(aes(y = pred_stress),
            colour = "blue",
            linewidth = 0.5,
            alpha = 0.85)+
  #facet_wrap(test_type~alloy_id, scales = "free")+
  ggh4x::facet_grid2(test_type~alloy_id, 
                     scales = "free",
                     independent = "y")+
  labs(x= TeX("Scaled Strain ($\\epsilon^{*}$)"),
       y = TeX("Stress $\\sigma$ (GPa)"),
       title = "Functional Prediction at End-of-Test")+
  theme(legend.position = "bottom",
        axis.text = element_text(size = 7),
        strip.text.x = element_text(size= 6))
```



```{r}
dat_alloy <- ss_dat_c_filtered%>%
                          arrange(alloy_rep_id)%>%
                          group_by(alloy_rep_id)%>%
                          slice_head(n=1)%>%
            ungroup()%>%
            select(alloy_rep_id,alloy,Mo,Nb,Ta,V,W, rep, Experiment, alloy_cnt)
```




```{r}


out_dat_t <- dat_orth_coefs_t%>%
              pivot_wider(names_from = "coef_names",
                          values_from = "val")%>%
              left_join(dat_alloy,
                        by = "alloy_rep_id")%>%
                ungroup()

export(out_dat_t,
       file =here::here("Results",
                        "ss_all_ort_coefs_t_uns.csv"))

out_dat_c <- dat_orth_coefs_c%>%
              pivot_wider(names_from = "coef_names",
                          values_from = "val")%>%
              left_join(dat_alloy,
                        by = "alloy_rep_id")%>%
                ungroup()

export(out_dat_c,
       file =here::here("Results",
                        "ss_all_ort_coefs_c_uns.csv"))
```


